
/*CONVERSION MINUTOS A HORAS*/
CREATE OR REPLACE FUNCTION MINUTE_TO_HOUR(NUMERO NUMBER) RETURN NUMBER IS
HORA NUMBER;
BEGIN  
  HORA:=TRUNC((NUMERO/60));
  RETURN (HORA);
END;
/*MOD DE MIN/60*/
CREATE OR REPLACE FUNCTION MOD_MINUTE(NUMERO NUMBER) RETURN NUMBER IS
HORA NUMBER;
BEGIN  
  HORA:=ROUND(MOD(NUMERO,60),2);
  RETURN (HORA);
END;
/*Suma de horas de la licencia*/
CREATE OR REPLACE FUNCTION SUMAR_HORAS_LICENCIA(SUMA NUMBER,NUMLICENCIA NUMBER) RETURN NUMBER IS
TIEMPOFINAL NUMBER;
BEGIN  
  SELECT NVL(HORAS_DE_VUELO,0)+SUMA INTO TIEMPOFINAL FROM LICENCIA WHERE NUMERO_LICENCIA=NUMLICENCIA;
  RETURN (TIEMPOFINAL);  
END;
/*Suma de minutos de la licencia*/
CREATE OR REPLACE FUNCTION SUMAR_MINUTOS_LICENCIA(SUMA NUMBER,NUMLICENCIA NUMBER) RETURN NUMBER IS
TIEMPOFINAL NUMBER;
BEGIN  
  SELECT NVL(MINUTOS_DE_VUELO,0)+SUMA INTO TIEMPOFINAL FROM LICENCIA WHERE NUMERO_LICENCIA=NUMLICENCIA;
  RETURN (TIEMPOFINAL);
END;

/*PRCEDIMIENTO ACTUALIZAR HORAS DE LICENCIA AL EJECUTAR PLAN DE VUELO REAL*/      
CREATE OR REPLACE PROCEDURE UPDATE_HORAS_LICENCIA AS
  CURSOR c1 IS 
      SELECT LICENCIA_PILOTO,HORA_VUELO_PILOTO,MINUTO_VUELO_PILOTO,LICENCIA_COPILOTO,
      HORA_VUELO_COPILOTO,MINUTO_VUELO_COPILOTO
      FROM PLAN_VUELO_REAL 
      WHERE ID_PLAN_VUELO_REAL=(SELECT MAX(ID_PLAN_VUELO_REAL) AS id FROM PLAN_VUELO_REAL);
  VALOR_H NUMBER;
  VALOR_M NUMBER;
BEGIN
  FOR j in c1
   LOOP
   /*UPDATE PILOTO*/
    VALOR_H:= MINUTE_TO_HOUR(SUMAR_MINUTOS_LICENCIA(j.MINUTO_VUELO_PILOTO,j.LICENCIA_PILOTO))+SUMAR_HORAS_LICENCIA(j.HORA_VUELO_PILOTO,j.LICENCIA_PILOTO);
    VALOR_M:=MOD_MINUTE(SUMAR_MINUTOS_LICENCIA(j.MINUTO_VUELO_PILOTO,j.LICENCIA_PILOTO));
    UPDATE LICENCIA SET HORAS_DE_VUELO = VALOR_H, MINUTOS_DE_VUELO = VALOR_M
    WHERE NUMERO_LICENCIA=j.LICENCIA_PILOTO;
    /*UPDATE COPILOTO*/
    VALOR_H:= MINUTE_TO_HOUR(SUMAR_MINUTOS_LICENCIA(j.MINUTO_VUELO_COPILOTO,j.LICENCIA_COPILOTO))+SUMAR_HORAS_LICENCIA(j.HORA_VUELO_COPILOTO,j.LICENCIA_COPILOTO);
    VALOR_M:=MOD_MINUTE(SUMAR_MINUTOS_LICENCIA(j.MINUTO_VUELO_COPILOTO,j.LICENCIA_COPILOTO));
    UPDATE LICENCIA SET HORAS_DE_VUELO = VALOR_H, MINUTOS_DE_VUELO = VALOR_M
    WHERE NUMERO_LICENCIA=j.LICENCIA_COPILOTO; 
   END LOOP;
END;



