
CREATE OR REPLACE PROCEDURE UPDATE_HORAS_AERONAVE AS
  CURSOR c1 IS 
      SELECT MATRICULA FROM AERONAVE;
  VALOR_H NUMBER;
  VALOR_M NUMBER;
  HORAS NUMBER;
  MINUTOS NUMBER;
BEGIN
  FOR j in c1
   LOOP
   SELECT NVL(SUM(extract( DAY FROM FECHA_DESTINO_REAL-FECHA_ORIGEN_REAL)*24+
      EXTRACT(HOUR FROM FECHA_DESTINO_REAL-FECHA_ORIGEN_REAL)+
      EXTRACT(HOUR FROM TIEMPO_TAXEO_SALIDA)+EXTRACT(HOUR FROM TIEMPO_TAXEO_LLEGADA)),0) INTO HORAS
      FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =j.MATRICULA;
      
    SELECT NVL(SUM(EXTRACT(MINUTE FROM FECHA_DESTINO_REAL-FECHA_ORIGEN_REAL)+
      EXTRACT(MINUTE FROM TIEMPO_TAXEO_SALIDA)+EXTRACT(MINUTE FROM TIEMPO_TAXEO_LLEGADA)),0)  INTO MINUTOS
      FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =j.MATRICULA;
   /*UPDATE AERONAVE*/
    VALOR_H:= HORAS+MINUTE_TO_HOUR(MINUTOS);      
    VALOR_M:=MOD_MINUTE(MINUTOS);
    UPDATE AERONAVE SET HORAS_VUELO = VALOR_H, MINUTOS_VUELO = VALOR_M
    WHERE MATRICULA=j.MATRICULA;
   END LOOP;
END;