
/*FUNCION DE CALCULO DE HORAS DE VUELO DE LOS COMPONENTES*/
CREATE OR REPLACE FUNCTION CALCULO_TIEMPO_COMPONENTE(ID_COMP NUMBER) RETURN INTERVAL DAY TO SECOND IS
TIEMPO INTERVAL DAY(2) TO SECOND(6);
BEGIN  
    SELECT NUMTODSINTERVAL(SUM(86400 *(trunc(FECHA_DESTINO_REAL) - trunc(FECHA_ORIGEN_REAL))
  + TO_NUMBER(TO_CHAR(FECHA_DESTINO_REAL,'sssss')) - TO_NUMBER(TO_CHAR(FECHA_ORIGEN_REAL,'sssss'))
  + TO_NUMBER(TO_CHAR(TIEMPO_TAXEO_LLEGADA,'sssss'))+ TO_NUMBER(TO_CHAR(TIEMPO_TAXEO_SALIDA,'sssss'))),'second') INTO TIEMPO
  FROM PLAN_VUELO_REAL,COMPONENTE
  WHERE PLAN_VUELO_REAL.FECHA_ORIGEN_REAL>=COMPONENTE.FECHA_INGRESO
  AND PLAN_VUELO_REAL.AERONAVE_MATRICULA = COMPONENTE.AERONAVE_MATRICULA
  AND COMPONENTE.ID_COMPONENTE = ID_COMP;
  RETURN (TIEMPO);  
END;
/*PRUEBA DEL CALCULO DE TIEMPO CON EL 1ER COMPONENTE
SELECT CALCULO_TIEMPO_COMPONENTE(1)FROM dual;*/

/*PROCEDIMIENTO DE ACTUALIZACION DE HORAS DE VUELO DEL COMPONENTE*/
CREATE OR REPLACE PROCEDURE UPDATE_TIEMPOCOMPONENTE(MATRICULA VARCHAR2) AS
  CURSOR c1 IS 
      SELECT  COMPONENTE.ID_COMPONENTE 
      FROM COMPONENTE 
      WHERE COMPONENTE.AERONAVE_MATRICULA=MATRICULA;
  VALOR INTERVAL DAY(2) TO SECOND(6);
BEGIN
  FOR j in c1
   LOOP
      VALOR := NVL(CALCULO_TIEMPO_COMPONENTE(j.ID_COMPONENTE),'+00 00:00:00.000000');
      UPDATE COMPONENTE SET HORASVUELO = VALOR WHERE ID_COMPONENTE=j.ID_COMPONENTE;      
   END LOOP;
END;
/*PRUEBA DEL PROCEDIMIENTO CON LA MATRICULA AB-123
EXECUTE UPDATE_TIEMPOCOMPONENTE('AB-123');*/


