using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Conexion;


namespace Logica
{
    public class consultas
    {
        
        
        public class Variables
        {
            //FORM INGRESO PILOTO

            public static string InsertPiloto = "INSERT INTO PILOTO (RUT_PILOTO,NOMBRE_PILOTO,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,CORREO,DIRECCION,TEL_FIJO,TEL_CEL,SEXO_ID_SEXO,COMUNA_ID_COMUNA,ESTADO_ID_ESTADO) VALUES";
            public static string SelectPiloto = "SELECT * FROM PILOTO WHERE RUT_PILOTO=";
            public static string SelectPilotoCorreo = "SELECT CORREO FROM PILOTO WHERE CORREO=";
            public static string SelectCboPais = "SELECT * FROM PAIS";
            public static string SelectCboRegion = "SELECT NOMBRE_REGION, ID_REGION FROM REGION INNER JOIN PAIS ON PAIS.ID_PAIS = REGION.PAIS_ID_PAIS WHERE NOMBRE_PAIS =";
            public static string SelectCboProvincia = "SELECT NOMBRE_PROVINCIA, ID_PROVINCIA FROM PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION WHERE NOMBRE_REGION =";
            public static string SelectCboComuna = "SELECT NOMBRE_COMUNA, ID_COMUNA FROM COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA WHERE NOMBRE_PROVINCIA =";
            public static string ValidarRUT = "SELECT RUT, TIPO_USUARIO_ID_TIPO_USUARIO FROM USUARIO WHERE RUT= ";
            public static string ValidarRUT2 = "AND TIPO_USUARIO_ID_TIPO_USUARIO IN (1,3,4)";
             //FIN FORM INGRESO PILOTO


             //FORM PLAN VUELO
            public static string estadoPiloto;
            public static string estado;
            public static string SelectCbAeronaveDisponible = "SELECT ESTADO_ID_ESTADO FROM AERONAVE WHERE MATRICULA =";
            public static string SelectCbPilotoDisponible = "SELECT ESTADO_ID_ESTADO FROM PILOTO WHERE RUT_PILOTO=";
            public static string SelectCbCopilotoDisponible = "SELECT ESTADO_ID_ESTADO FROM PILOTO WHERE RUT_PILOTO=";
            public static string SelectCboCondicion = "SELECT * FROM CONDICION";
            public static string SelectCboMision = "SELECT * FROM MISION";
            public static string SelectCboTipoLicencia = "SELECT NOMBRE_TIPO_LICENCIA, NUMERO_LICENCIA FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string SelectCboTipoLicencia2 = "SELECT NOMBRE_TIPO_LICENCIA, NUMERO_LICENCIA FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string SelectTodosPilotos = "SELECT * FROM PILOTO";
            public static string SelectCboTipoAeronave = "SELECT * FROM TIPO_AERONAVE";
            public static string SelectCboAeronave = "SELECT NOMBRE_MODELO, MATRICULA, ESTADO_ID_ESTADO FROM AERONAVE INNER JOIN TIPO_AERONAVE ON AERONAVE.TIPO_AERONAVE_ID_TIPO_AERONAVE = TIPO_AERONAVE.ID_TIPO_AERONAVE INNER JOIN MODELO ON AERONAVE.MODELO_ID_MODELO = MODELO.ID_MODELO WHERE NOMBRE_TIPO_AERONAVE =";
            public static string SelectCboOrigen = "SELECT NOMBRE_ORIGEN, ID_ORIGEN FROM ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA WHERE NOMBRE_COMUNA =";
            public static string SelectCboDestino = "SELECT NOMBRE_DESTINO, ID_DESTINO FROM DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA WHERE NOMBRE_COMUNA =";
            public static string IngresoPlanVuelo = "INSERT INTO PLAN_VUELO (ID_VUELO,DESCRIPCION,FECHA_ORIGEN_ESTIMADA,FECHA_DESTINO_ESTIMADA,CONDICION_ID_CONDICION,MISION_ID_MISION,PILOTO_RUT_PILOTO,RUT_COPILOTO,LICENCIA_PILOTO,LICENCIA_COPILOTO,RUTA,DESTINO_ID_DESTINO,ORIGEN_ID_ORIGEN,AERONAVE_MATRICULA) VALUES";
            //FIN FORM PLAN VUELO

            //FORM INGRESO DETALLE MANTENIMIENTO
            public static string FillCboTallerMecanico = "SELECT * FROM TALLER_MECANICO";
            public static string FillCboAeronaveDetalleMantenimiento = "SELECT NOMBRE_MODELO, MATRICULA FROM AERONAVE INNER JOIN MODELO ON AERONAVE.MODELO_ID_MODELO = MODELO.ID_MODELO";
            public static string FillCboMantenimientoDetalleMantenimiento = "SELECT ID_MANTENIMIENTO,HORAS_VUELO FROM MANTENIMIENTO ";
            public static string InsertarDetalleMantenimiento = "INSERT INTO DETALLE_MANTENIMIENTO VALUES";
            public static string ValidarMantenimiento = "SELECT MATRICULA, ESTADO_ID_ESTADO FROM AERONAVE WHERE MATRICULA=";
            public static string ValidarMatenimiento2 = "AND ESTADO_ID_ESTADO=2";
            public static string UpdateAeronaveToEstado3 = "UPDATE AERONAVE SET ESTADO_ID_ESTADO = 3 WHERE MATRICULA=";
            public static string RecorrerAeronaveBuscandoEstado3 = "SELECT NOMBRE_TIPO_AERONAVE,MATRICULA,NOMBRE_MODELO,ANO_FABRICACION,FECHA_TERMINO,ESTADO_ID_ESTADO FROM AERONAVE A,DETALLE_MANTENIMIENTO DM,MANTENIMIENTO MT,MODELO MO,TIPO_AERONAVE TA WHERE A.MATRICULA = DM.AERONAVE_MATRICULA AND MO.ID_MODELO = A.MODELO_ID_MODELO AND TA.ID_TIPO_AERONAVE = A.TIPO_AERONAVE_ID_TIPO_AERONAVE AND DM.MANTENIMIENTO_ID_MANTENIMIENTO = MT.ID_MANTENIMIENTO AND ESTADO_ID_ESTADO = 3";
            public static string AgruparCorreosDePilotos = "SELECT  LISTAGG(CORREO, ', ') WITHIN GROUP (ORDER BY CORREO) AS CORREOS FROM PILOTO WHERE SEXO_ID_SEXO IN ('1','2')";
            public static string UpdateAeronaveToEstado2 = "UPDATE AERONAVE SET ESTADO_ID_ESTADO = 2 WHERE MATRICULA=";
            //FIN FORM INGRESO DETALLE MANTENIMIENTO

            //FORM MANTENEDOR AERONAVE
            public static string MostrarAeronaveMantenedorAeronave = "SELECT MATRICULA,FECHA_INSPECCION_ANUAL,ANO_FABRICACION,NOMBRE_TIPO_AERONAVE,NOMBRE_FABRICANTE,NOMBRE_MODELO,NOMBRE_ESTADO FROM AERONAVE INNER JOIN TIPO_AERONAVE ON TIPO_AERONAVE.ID_TIPO_AERONAVE = AERONAVE.TIPO_AERONAVE_ID_TIPO_AERONAVE INNER JOIN FABRICANTE ON FABRICANTE.ID_FABRICANTE = AERONAVE.FABRICANTE_ID_FABRICANTE INNER JOIN MODELO ON MODELO.ID_MODELO = AERONAVE.MODELO_ID_MODELO INNER JOIN ESTADO ON ESTADO.ID_ESTADO = AERONAVE.ESTADO_ID_ESTADO WHERE MATRICULA=";
            public static string SelectCboAeronaveMatenedorAeronave = "SELECT * FROM TIPO_AERONAVE";
            public static string SelectCboFabricanteMantenedorAeronave = "SELECT * FROM FABRICANTE";
            public static string SelectCboProveedorMantenedorAeronave = "SELECT * FROM PROVEEDOR";
            public static string LlenarGridMatenedorAeronave = "SELECT ID_COMPONENTE AS ID, NOMBRE_COMPONENTE AS NOMBRE FROM COMPONENTE, PROVEEDOR WHERE AERONAVE_MATRICULA =";
            public static string LlenarGridMatenedorAeronave2 = "AND PROVEEDOR_ID_PROVEEDOR=ID_PROVEEDOR ORDER BY ID_COMPONENTE ASC";
            public static string CellComponentes = "SELECT * FROM COMPONENTE,PROVEEDOR WHERE ID_COMPONENTE = {0} AND ID_PROVEEDOR = PROVEEDOR_ID_PROVEEDOR";
            public static string ModificarComponente = "UPDATE COMPONENTE SET NOMBRE_COMPONENTE = ";
            public static string ModificarComponente2 = "DESCRIPCION = ";
            public static string ModificarComponente3 = "PROVEEDOR_ID_PROVEEDOR = ";
            public static string ModificarComponente4 = "WHERE ID_COMPONENTE = ";
            public static string EliminarComponente = "DELETE FROM COMPONENTE WHERE ID_COMPONENTE=";
            public static string ModificarAeronave = "UPDATE AERONAVE SET ANO_FABRICACION = ";
            public static string ModificarAeronave2 = "TIPO_AERONAVE_ID_TIPO_AERONAVE = ";
            public static string ModificarAeronave3 = "FABRICANTE_ID_FABRICANTE = ";
            public static string ModificarAeronave4 = "WHERE MATRICULA = ";
            public static string EliminarAeronave = "DELETE FROM AERONAVE WHERE MATRICULA=";
            public static string FillCboDisponibilidadEditFormMantenedorAeronave= "SELECT * FROM estado WHERE rownum <= 2";
            //FIN FORM MANTENEDOR AERONAVE


            //FORM PLAN VUELO REAL
            public static string PlanVueloRealSelectCboCondicion = "SELECT ID_VUELO, ID_CONDICION, NOMBRE_CONDICION FROM PLAN_VUELO INNER JOIN CONDICION ON PLAN_VUELO.CONDICION_ID_CONDICION = CONDICION.ID_CONDICION WHERE ID_VUELO=";
            public static string PlanVueloRealSelectCboCondicionEdit = "SELECT * FROM CONDICION";
            public static string PlanVueloRealCboTipoLicenciaPiloto = "SELECT PILOTO_RUT_PILOTO, NOMBRE_TIPO_LICENCIA, LICENCIA_PILOTO, NUMERO_LICENCIA FROM PLAN_VUELO,(SELECT NOMBRE_TIPO_LICENCIA, NUMERO_LICENCIA FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string PlanVueloRealCboTipoLicenciaPiloto2 = "WHERE PILOTO_RUT_PILOTO =";
            public static string PlanVueloRealCboTipoLicenciaPiloto3 = "AND ID_VUELO=";
            public static string PlanVueloRealCboTipoLicenciaPiloto4 = "AND LICENCIA_PILOTO=NUMERO_LICENCIA";
            public static string PlanVueloRealCboTipoLicenciaCopiloto = "SELECT RUT_COPILOTO, NOMBRE_TIPO_LICENCIA, LICENCIA_COPILOTO, NUMERO_LICENCIA FROM PLAN_VUELO,(SELECT NOMBRE_TIPO_LICENCIA, NUMERO_LICENCIA FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string PlanVueloRealCboTipoLicenciaCopiloto2 = "WHERE RUT_COPILOTO =";
            public static string PlanVueloRealCboTipoLicenciaCopiloto3 = "AND ID_VUELO=";
            public static string PlanVueloRealCboTipoLicenciaCopiloto4 = "AND LICENCIA_COPILOTO=NUMERO_LICENCIA";
            public static string PlanVueloRealCboPiloto = "SELECT PILOTO_RUT_PILOTO, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO FROM  PLAN_VUELO INNER JOIN PILOTO ON PLAN_VUELO.PILOTO_RUT_PILOTO = PILOTO.RUT_PILOTO WHERE ID_VUELO=";
            public static string PlanVueloRealCboCopiloto = "SELECT RUT_COPILOTO,NOMBRE_PILOTO,APELLIDO_PATERNO,APELLIDO_MATERNO FROM PILOTO INNER JOIN SEXO ON PILOTO.SEXO_ID_SEXO = SEXO.ID_SEXO INNER JOIN COMUNA ON PILOTO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PLAN_VUELO ON PLAN_VUELO.RUT_COPILOTO = PILOTO.RUT_PILOTO  WHERE ID_VUELO=";
            public static string PlanVueloRealCboTipoAeronave = "SELECT AERONAVE_MATRICULA, NOMBRE_TIPO_AERONAVE, ID_VUELO FROM PLAN_VUELO INNER JOIN AERONAVE ON PLAN_VUELO.AERONAVE_MATRICULA = AERONAVE.MATRICULA INNER JOIN TIPO_AERONAVE ON AERONAVE.TIPO_AERONAVE_ID_TIPO_AERONAVE = TIPO_AERONAVE.ID_TIPO_AERONAVE WHERE ID_VUELO=";
            public static string PlanVueloRealCboAeronave = "SELECT NOMBRE_MODELO, AERONAVE_MATRICULA, NOMBRE_TIPO_AERONAVE, ID_VUELO FROM PLAN_VUELO INNER JOIN AERONAVE ON PLAN_VUELO.AERONAVE_MATRICULA = AERONAVE.MATRICULA INNER JOIN TIPO_AERONAVE ON AERONAVE.TIPO_AERONAVE_ID_TIPO_AERONAVE = TIPO_AERONAVE.ID_TIPO_AERONAVE INNER JOIN MODELO ON AERONAVE.MODELO_ID_MODELO = MODELO.ID_MODELO WHERE ID_VUELO=";
            public static string PlanVueloRealCboAeronave2 = "AND NOMBRE_TIPO_AERONAVE=";
            public static string PlanVueloRealOrigenPais = "SELECT ID_VUELO, ID_PAIS, NOMBRE_PAIS FROM PLAN_VUELO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealOrigenPaisEdit = "SELECT * FROM PAIS";
            public static string PlanVueloRealOrigenRegion = "SELECT ID_VUELO, ID_REGION, NOMBRE_REGION FROM PLAN_VUELO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealOrigenRegionEdit = "SELECT NOMBRE_REGION, ID_REGION FROM REGION INNER JOIN PAIS ON PAIS.ID_PAIS = REGION.PAIS_ID_PAIS WHERE NOMBRE_PAIS =";
            public static string PlanVueloRealOrigenProvincia = "SELECT ID_VUELO, ID_PROVINCIA, NOMBRE_PROVINCIA FROM PLAN_VUELO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealOrigenProvinciaEdit = "SELECT NOMBRE_PROVINCIA, ID_PROVINCIA FROM PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION WHERE NOMBRE_REGION =";
            public static string PlanVueloRealOrigenComuna = "SELECT ID_VUELO, ID_COMUNA, NOMBRE_COMUNA FROM PLAN_VUELO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealOrigenComunaEdit = "SELECT NOMBRE_COMUNA, ID_COMUNA FROM COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA WHERE NOMBRE_PROVINCIA =";
            public static string PlanVueloRealOrigen = "SELECT ID_VUELO, ID_ORIGEN, NOMBRE_ORIGEN FROM PLAN_VUELO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealOrigenEdit = "SELECT NOMBRE_ORIGEN, ID_ORIGEN FROM ORIGEN INNER JOIN COMUNA ON ORIGEN.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA WHERE NOMBRE_COMUNA =";
            public static string PlanVueloRealDestinoPais = "SELECT ID_VUELO, ID_PAIS, NOMBRE_PAIS FROM PLAN_VUELO INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealDestinoPaisEdit = "SELECT * FROM PAIS";
            public static string PlanVueloRealDestinoRegion = "SELECT ID_VUELO, ID_REGION, NOMBRE_REGION FROM PLAN_VUELO INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealDestinoRegionEdit = "SELECT NOMBRE_REGION, ID_REGION FROM REGION INNER JOIN PAIS ON PAIS.ID_PAIS = REGION.PAIS_ID_PAIS WHERE NOMBRE_PAIS =";
            public static string PlanVueloRealDestinoProvincia = "SELECT ID_VUELO, ID_PROVINCIA, NOMBRE_PROVINCIA FROM PLAN_VUELO INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealDestinoProvinciaEdit = "SELECT NOMBRE_PROVINCIA, ID_PROVINCIA FROM PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION WHERE NOMBRE_REGION =";
            public static string PlanVueloRealDestinoComuna = "SELECT ID_VUELO, ID_COMUNA, NOMBRE_COMUNA FROM PLAN_VUELO INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealDestinoComunaEdit = "SELECT NOMBRE_COMUNA, ID_COMUNA FROM COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA WHERE NOMBRE_PROVINCIA =";
            public static string PlanVueloRealFillCbDestino = "SELECT ID_VUELO, ID_DESTINO, NOMBRE_DESTINO FROM PLAN_VUELO INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA INNER JOIN PROVINCIA ON COMUNA.PROVINCIA_ID_PROVINCIA = PROVINCIA.ID_PROVINCIA INNER JOIN REGION ON PROVINCIA.REGION_ID_REGION = REGION.ID_REGION INNER JOIN PAIS ON REGION.PAIS_ID_PAIS = PAIS.ID_PAIS WHERE ID_VUELO=";
            public static string PlanVueloRealFillCbDestinoEdit = "SELECT NOMBRE_DESTINO, ID_DESTINO FROM DESTINO INNER JOIN COMUNA ON DESTINO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA WHERE NOMBRE_COMUNA =";
            public static string VerificarIDVuelo = "SELECT PLAN_VUELO_ID_VUELO FROM PLAN_VUELO_REAL WHERE PLAN_VUELO_ID_VUELO=";
            public static string InsertPlanVueloReal = "INSERT INTO PLAN_VUELO_REAL (ID_PLAN_VUELO_REAL,DESCRIPCION,FECHA_ORIGEN_REAL,FECHA_DESTINO_REAL,TIEMPO_TAXEO_SALIDA,TIEMPO_TAXEO_LLEGADA,RUT_PILOTO_PVR,RUT_COPILOTO,LICENCIA_PILOTO,LICENCIA_COPILOTO,HORA_VUELO_PILOTO,HORA_VUELO_COPILOTO,MINUTO_VUELO_PILOTO,MINUTO_VUELO_COPILOTO,RUTA,ORIGEN_ID_ORIGEN,DESTINO_ID_DESTINO,AERONAVE_MATRICULA,MISION_ID_MISION,CONDICION_ID_CONDICION,PLAN_VUELO_ID_VUELO) VALUES";
            public static string BtnConsultar = "SELECT * FROM PLAN_VUELO WHERE ID_VUELO=";
            public static string BtnVuelos = "SELECT ID_VUELO,FECHA_ORIGEN_ESTIMADA,FECHA_DESTINO_ESTIMADA,PILOTO_RUT_PILOTO RUT_PILOTO,RUT_COPILOTO,NOMBRE_ORIGEN ORIGEN,NOMBRE_DESTINO DESTINO,AERONAVE_MATRICULA MATRICULA_AERONAVE FROM PLAN_VUELO INNER JOIN PILOTO ON PLAN_VUELO.PILOTO_RUT_PILOTO = PILOTO.RUT_PILOTO INNER JOIN ORIGEN ON PLAN_VUELO.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN DESTINO ON PLAN_VUELO.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN AERONAVE ON PLAN_VUELO.AERONAVE_MATRICULA = AERONAVE.MATRICULA";
            //FIN FORM PLAN_VUELO REAL


            //FORM INGRESAR AERONAVE
            public static string SelectTipoAeronaveFormIngresarAeronave = "SELECT * FROM TIPO_AERONAVE";
            public static string SelectFabricanteFormIngresarAeronave = "SELECT * FROM FABRICANTE";
            public static string SelectModeloFormIngresarAeronave = "SELECT * FROM MODELO";
            public static string ValidarMatriculaFormIngresarAeronave = "SELECT * FROM AERONAVE WHERE MATRICULA =";
            public static string SelectEstadoFormIngresarAeronave = "SELECT * FROM estado WHERE rownum <= 2";
            public static string InsertAeronaveFormIngresarAeronave = "INSERT INTO AERONAVE (MATRICULA,FECHA_INSPECCION_ANUAL,ANO_FABRICACION,TIPO_AERONAVE_ID_TIPO_AERONAVE,FABRICANTE_ID_FABRICANTE,MODELO_ID_MODELO,ESTADO_ID_ESTADO) VALUES";
            //FIN FORM INGRESAR AERONAVE


            //FORM INGRESAR COMPONENTE
            public static string SelectCbMatricula = "SELECT * FROM AERONAVE";
            public static string SelectCbProveedor = "SELECT * FROM PROVEEDOR";
            public static string SelectComponente = "SELECT * FROM COMPONENTE";
            public static string InsertComponente = "INSERT INTO COMPONENTE (ID_COMPONENTE,NOMBRE_COMPONENTE,DESCRIPCION,PROVEEDOR_ID_PROVEEDOR,AERONAVE_MATRICULA) VALUES";
            //FIN FORM INGRESAR COMPONENTE


            //FORM IGNRESAR LICENCIA
            public static string SelectCboLicencia = "SELECT * FROM TIPO_LICENCIA";
            public static string SelectTodosPilotosFormLicencia = "SELECT * FROM PILOTO";
            public static string SelectLicenciaNumeroLicencia = "SELECT * FROM LICENCIA WHERE NUMERO_LICENCIA=";
            public static string ValidarPilotoLicencia = "SELECT RUT_PILOTO, TIPO_LICENCIA_ID_TIPO_LICENCIA FROM PILOTO INNER JOIN LICENCIA ON PILOTO.RUT_PILOTO = LICENCIA.PILOTO_RUT_PILOTO WHERE PILOTO_RUT_PILOTO =";
            public static string ValidarPilotoLicencia2 = "AND TIPO_LICENCIA_ID_TIPO_LICENCIA =";
            public static string InsertLicencia = "INSERT INTO LICENCIA (NUMERO_LICENCIA,DESCRIPCION,FECHA_EXPIRACION,PILOTO_RUT_PILOTO,TIPO_LICENCIA_ID_TIPO_LICENCIA) VALUES";
            //FIN FORM INGRESAR LICENCIA



            //MANTENEDOR LICENCIA
            public static string SelectFormMantenedorLicencia = "SELECT NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_SEXO FROM PILOTO INNER JOIN SEXO ON PILOTO.SEXO_ID_SEXO = SEXO.ID_SEXO WHERE RUT_PILOTO=";
            public static string SelectCboTipoLicenciaFormMantenedorLicencia = "SELECT * FROM TIPO_LICENCIA";
            public static string dgvLicenciasx = "SELECT * FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE LICENCIA.NUMERO_LICENCIA = {0}";
            public static string SelectNombreSexo = "SELECT NUMERO_LICENCIA AS NUMERO, NOMBRE_TIPO_LICENCIA AS TIPO FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string SelectNombreSexo2 = "ORDER BY LICENCIA.NUMERO_LICENCIA ASC";
            public static string EliminarLicencia = "DELETE FROM LICENCIA WHERE NUMERO_LICENCIA=";
		    public static string ModificarLicencia1 = "UPDATE LICENCIA SET DESCRIPCION =";
		    public static string ModificarLicencia2 = "TIPO_LICENCIA_ID_TIPO_LICENCIA = ";
		    public static string ModificarLicencia3 = "WHERE NUMERO_LICENCIA = ";
            //FIN MANTENEDOR LICENCIA



            //MANTENEDOR PILOTO
            public static string SelectPilotoWhereRutPiloto = "SELECT * FROM PILOTO WHERE RUT_PILOTO=";
            public static string ValidarCorreoAndPiloto = "SELECT CORREO, RUT_PILOTO FROM PILOTO WHERE CORREO=";
            public static string ValidarCorreoAndPiloto2 = "AND RUT_PILOTO =";
            public static string ValidarCorreoMantenedorPiloto = "SELECT CORREO, RUT_PILOTO FROM PILOTO WHERE CORREO=";
            public static string ActualizarPiloto= "UPDATE PILOTO SET NOMBRE_PILOTO = ";
            public static string ActualizarPiloto2= "APELLIDO_PATERNO = ";
            public static string ActualizarPiloto3= "APELLIDO_MATERNO = ";
            public static string ActualizarPiloto4= "FECHA_NACIMIENTO = ";
            public static string ActualizarPiloto5= "CORREO = ";
            public static string ActualizarPiloto6= "DIRECCION = ";
            public static string ActualizarPiloto7= "TEL_FIJO = ";
            public static string ActualizarPiloto8= "TEL_CEL = ";
            public static string ActualizarPiloto9= "ESTADO_ID_ESTADO=";
            public static string ActualizarPiloto10= "WHERE RUT_PILOTO = ";
            public static string SelectPilotoMantenedorPiloto = "SELECT RUT_PILOTO RUT,NOMBRE_PILOTO NOMBRE,APELLIDO_PATERNO APELLIDO_PATERNO,APELLIDO_MATERNO APELLIDO_MATERNO,FECHA_NACIMIENTO,CORREO,DIRECCION,TEL_FIJO TELEFONO_FIJO,TEL_CEL CELULAR,NOMBRE_SEXO SEXO,NOMBRE_COMUNA COMUNA FROM PILOTO INNER JOIN SEXO ON PILOTO.SEXO_ID_SEXO = SEXO.ID_SEXO INNER JOIN COMUNA ON PILOTO.COMUNA_ID_COMUNA = COMUNA.ID_COMUNA";
            public static string FillCboDisponibilidad = "SELECT RUT_PILOTO, ESTADO_ID_ESTADO, NOMBRE_ESTADO FROM ESTADO INNER JOIN PILOTO ON ESTADO.ID_ESTADO = PILOTO.ESTADO_ID_ESTADO WHERE RUT_PILOTO=";
            public static string FillCboDisponibilidadEdit= "SELECT * FROM estado WHERE rownum <= 2";
            //FIN MANTENEDOR PILOTO



            //FORM INGRESAR FICHA MEDICA
            public static string SelectTodosPilotosFormFichaMedica = "SELECT * FROM PILOTO";
            public static string ValidaRutFormFichaMedica = "SELECT PILOTO_RUT_PILOTO FROM FICHA_MEDICA WHERE PILOTO_RUT_PILOTO=";
            public static string InsertFichaMedica = "INSERT INTO FICHA_MEDICA (ID_FICHA_MEDICA,FECHA_VENCIMIENTO,DESCRIPCION,PILOTO_RUT_PILOTO) VALUES";
            public static string UpdatePilotoHabilitar = "UPDATE PILOTO SET ESTADO_ID_ESTADO=1 WHERE RUT_PILOTO=";
            //FIN INGRESAR FICHA MEDICA

            //FORM INGRESAR USUARIO
            public static string InsertUsuarios = "INSERT INTO USUARIO (RUT,CONTRASENA,TIPO_USUARIO_ID_TIPO_USUARIO) VALUES";
            public static string SelectCboTipoU = "SELECT * FROM TIPO_USUARIO";
            public static string SelectUsuario = "SELECT * FROM USUARIO WHERE RUT=";
            public static string ValidarExistenciaPiloto = "SELECT RUT_PILOTO FROM PILOTO WHERE RUT_PILOTO=";
            //FIN INGRESAR USUARIO


            //LOGIN
            public static string CorreoFichaMedica = "SELECT  LISTAGG(CORREO, ', ') WITHIN GROUP (ORDER BY CORREO) AS CORREOS FROM PILOTO WHERE ESTADO_ID_ESTADO=3";
            public static string CorreoInactividad = "SELECT  LISTAGG(CORREO, ', ') WITHIN GROUP (ORDER BY CORREO) AS CORREOS FROM PILOTO WHERE ESTADO_ID_ESTADO=4";
            public static string UpdateCorreoFichaMedica = "UPDATE PILOTO SET ESTADO_ID_ESTADO=2 WHERE ESTADO_ID_ESTADO=3";
            public static string UpdateCorreoInactividad = "UPDATE PILOTO SET ESTADO_ID_ESTADO=2 WHERE ESTADO_ID_ESTADO=4";
            public static string ValidarEstadoPilotoLogin = "SELECT ESTADO_ID_ESTADO, RUT_PILOTO FROM PILOTO WHERE RUT_PILOTO= ";
            public static string ValidarEstadoPilotoLogin2 = "AND ESTADO_ID_ESTADO=2";
            //LOGIN

            //CONSULTAR HORAS VUELO AERONAVE
            public static string SelectCboAeronaveFormConsultarHorasVueloAeronave = "SELECT * FROM AERONAVE";
            public static string ConsultarHorasVueloAeronave1 = "SELECT EXTRACT(HOUR FROM FECHA_DESTINO_REAL-FECHA_ORIGEN_REAL) AS HORAS,EXTRACT(MINUTE FROM FECHA_DESTINO_REAL-FECHA_ORIGEN_REAL)  AS MINUTOS FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =";
            public static string ConsultarHorasVueloAeronave2 = "SELECT EXTRACT(HOUR FROM TIEMPO_TAXEO_SALIDA) AS HORAS,EXTRACT(MINUTE FROM TIEMPO_TAXEO_SALIDA) AS MINUTOS FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =";
            public static string ConsultarHorasVueloAeronave3 = "SELECT EXTRACT(HOUR FROM TIEMPO_TAXEO_LLEGADA)AS HORAS,EXTRACT(MINUTE FROM TIEMPO_TAXEO_LLEGADA)AS MINUTOS FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =";
            //FIN CONSULTAR HORAS VUELO AERONAVE

            //MANTENEDOR FORM FICHA MEDICA
            public static string SelectFromFichaMedica = "SELECT * FROM FICHA_MEDICA WHERE PILOTO_RUT_PILOTO=";
            public static string MostrarFichaMedica = "SELECT PILOTO_RUT_PILOTO RUT_PILOTO, NOMBRE_PILOTO NOMBRE, APELLIDO_PATERNO APELLIDO_PATERNO, APELLIDO_MATERNO APELLIDO_MATERNO, ID_FICHA_MEDICA, FECHA_VENCIMIENTO, DESCRIPCION FROM PILOTO INNER JOIN FICHA_MEDICA ON PILOTO.RUT_PILOTO = FICHA_MEDICA.PILOTO_RUT_PILOTO";
            public static string UpdateFichaMedica = "UPDATE FICHA_MEDICA SET DESCRIPCION = ";
            public static string UpdateFichaMedica2 = "WHERE ID_FICHA_MEDICA = ";
            public static string DeleteFichaMedica = "DELETE FROM FICHA_MEDICA WHERE ID_FICHA_MEDICA=";
            //FIN FORM MANTENEDOR FICHA MEDICA

            //CONSULTAR HORAS DE VUELO PILOTO
            public static string ConsultarHorasVueloPilotoCboTipoLicencia = "SELECT NOMBRE_TIPO_LICENCIA, NUMERO_LICENCIA FROM LICENCIA INNER JOIN TIPO_LICENCIA ON LICENCIA.TIPO_LICENCIA_ID_TIPO_LICENCIA = TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE PILOTO_RUT_PILOTO =";
            public static string ConsultarHorasVueloPilotoCboPiloto = "SELECT * FROM PILOTO";
            public static string ConsultarHorasVueloPiloto = "SELECT ID_PLAN_VUELO_REAL AS ID,HORA_VUELO_PILOTO AS HORAS, MINUTO_VUELO_PILOTO AS MINUTOS FROM PLAN_VUELO_REAL WHERE RUT_PILOTO_PVR = ";
            public static string ConsultarHorasVueloPiloto2 = "SELECT ID_PLAN_VUELO_REAL AS ID,HORA_VUELO_COPILOTO AS HORAS, MINUTO_VUELO_COPILOTO AS MINUTOS FROM PLAN_VUELO_REAL WHERE RUT_COPILOTO = ";
            public static string ConsultarHorasVueloPiloto3 = "SELECT ID_PLAN_VUELO_REAL AS ID,HORA_VUELO_PILOTO AS HORAS,MINUTO_VUELO_PILOTO AS MINUTOS FROM PLAN_VUELO_REAL WHERE RUT_PILOTO_PVR = ";
            public static string ConsultarHorasVueloPiloto3_1 = "AND LICENCIA_PILOTO =";
            public static string ConsultarHorasVueloPiloto4 = "SELECT ID_PLAN_VUELO_REAL AS ID,HORA_VUELO_COPILOTO AS HORAS,MINUTO_VUELO_COPILOTO AS MINUTOS FROM PLAN_VUELO_REAL WHERE RUT_COPILOTO = ";
            public static string ConsultarHorasVueloPiloto4_1 = "AND LICENCIA_COPILOTO =";
            //FIN CONSULTAR HORAS DE VUELO PILOTO

            //FORM REPORTE PILOTO
            public static string ReportePilotoAvion = "SELECT NUMERO_LICENCIA, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO, TO_CHAR(FECHA_VENCIMIENTO, 'dd/MM/yyyy')  AS FECHA_VENCIMIENTO, TO_CHAR(FECHA_DESTINO_REAL, 'dd/MM/yyyy') AS FECHA_DESTINO_REAL, RUT_PILOTO_PVR, NOMBRE_TIPO_AERONAVE FROM PILOTO P, LICENCIA LI , FICHA_MEDICA FM, PLAN_VUELO_REAL PVR, AERONAVE A, TIPO_AERONAVE TA WHERE P.RUT_PILOTO= LI.PILOTO_RUT_PILOTO AND P.RUT_PILOTO= FM.PILOTO_RUT_PILOTO AND PVR.AERONAVE_MATRICULA= A.MATRICULA AND A.TIPO_AERONAVE_ID_TIPO_AERONAVE = TA.ID_TIPO_AERONAVE AND P.RUT_PILOTO= PVR.RUT_PILOTO_PVR AND ROWNUM= 1 AND RUT_PILOTO_PVR=";
            public static string ReportePilotoAvion2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE   = 1 UNION ALL SELECT NUMERO_LICENCIA, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO, TO_CHAR(FECHA_VENCIMIENTO, 'dd/MM/yyyy')  AS FECHA_VENCIMIENTO, TO_CHAR(FECHA_DESTINO_REAL, 'dd/MM/yyyy') AS FECHA_DESTINO_REAL, RUT_COPILOTO, NOMBRE_TIPO_AERONAVE FROM PILOTO P, LICENCIA LI , FICHA_MEDICA FM, PLAN_VUELO_REAL PVR, AERONAVE A, TIPO_AERONAVE TA WHERE P.RUT_PILOTO= LI.PILOTO_RUT_PILOTO AND P.RUT_PILOTO= FM.PILOTO_RUT_PILOTO AND PVR.AERONAVE_MATRICULA= A.MATRICULA AND A.TIPO_AERONAVE_ID_TIPO_AERONAVE = TA.ID_TIPO_AERONAVE AND P.RUT_PILOTO= PVR.RUT_COPILOTO AND ROWNUM= 1 AND RUT_COPILOTO=";
            public static string ReportePilotoAvion3 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE = 1 ORDER BY FECHA_DESTINO_REAL DESC";
            public static string ReportePilotoHelic = "SELECT NUMERO_LICENCIA, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO, TO_CHAR(FECHA_VENCIMIENTO, 'dd/MM/yyyy')  AS FECHA_VENCIMIENTO, TO_CHAR(FECHA_DESTINO_REAL, 'dd/MM/yyyy') AS FECHA_DESTINO_REAL, RUT_PILOTO_PVR, NOMBRE_TIPO_AERONAVE FROM PILOTO P, LICENCIA LI , FICHA_MEDICA FM, PLAN_VUELO_REAL PVR, AERONAVE A, TIPO_AERONAVE TA WHERE P.RUT_PILOTO= LI.PILOTO_RUT_PILOTO AND P.RUT_PILOTO= FM.PILOTO_RUT_PILOTO AND PVR.AERONAVE_MATRICULA= A.MATRICULA AND A.TIPO_AERONAVE_ID_TIPO_AERONAVE = TA.ID_TIPO_AERONAVE AND P.RUT_PILOTO= PVR.RUT_PILOTO_PVR AND ROWNUM= 1 AND RUT_PILOTO_PVR=";
            public static string ReportePilotoHelic2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE   = 2 UNION ALL SELECT NUMERO_LICENCIA, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO, TO_CHAR(FECHA_VENCIMIENTO, 'dd/MM/yyyy')  AS FECHA_VENCIMIENTO, TO_CHAR(FECHA_DESTINO_REAL, 'dd/MM/yyyy') AS FECHA_DESTINO_REAL, RUT_COPILOTO, NOMBRE_TIPO_AERONAVE FROM PILOTO P, LICENCIA LI , FICHA_MEDICA FM, PLAN_VUELO_REAL PVR, AERONAVE A, TIPO_AERONAVE TA WHERE P.RUT_PILOTO= LI.PILOTO_RUT_PILOTO AND P.RUT_PILOTO= FM.PILOTO_RUT_PILOTO AND PVR.AERONAVE_MATRICULA= A.MATRICULA AND A.TIPO_AERONAVE_ID_TIPO_AERONAVE = TA.ID_TIPO_AERONAVE AND P.RUT_PILOTO= PVR.RUT_COPILOTO AND ROWNUM= 1 AND RUT_COPILOTO=";
            public static string ReportePilotoHelic3 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE = 2 ORDER BY FECHA_DESTINO_REAL DESC";
            public static string ValidarFichaMedicaReportePiloto = "SELECT ID_FICHA_MEDICA, PILOTO_RUT_PILOTO FROM FICHA_MEDICA WHERE PILOTO_RUT_PILOTO=";
            //FIN FORM REPORTE PILOTO

            //FORM REPORTE AERONAVES
            public static string ValidarTipoAeronaveFormReporte = "SELECT MATRICULA, TIPO_AERONAVE_ID_TIPO_AERONAVE FROM AERONAVE WHERE MATRICULA=";
            public static string ValidarTipoAeronaveFormReporte2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE = 1";
            public static string DatosAvion = "SELECT MATRICULA, TO_CHAR(FECHA_INSPECCION_ANUAL,'DD/MM/YYYY') FECHA_INSPECCION_ANUAL,TO_CHAR(FECHA_DESTINO_REAL,'DD/MM/YYYY') FECHA_ULTIMO_VUELO,TRUNC(SYSDATE)-FECHA_INSPECCION_ANUAL DIAS_PARA_INSPECCION FROM AERONAVE INNER JOIN PLAN_VUELO ON AERONAVE.MATRICULA = PLAN_VUELO.AERONAVE_MATRICULA INNER JOIN PLAN_VUELO_REAL ON PLAN_VUELO.ID_VUELO = PLAN_VUELO_REAL.PLAN_VUELO_ID_VUELO WHERE ROWNUM = 1 AND MATRICULA=";
            public static string DatosAvion2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE=1 ORDER BY FECHA_DESTINO_REAL DESC";
            public static string ValidarTipoAeronaveFormReporteH = "SELECT MATRICULA, TIPO_AERONAVE_ID_TIPO_AERONAVE FROM AERONAVE WHERE MATRICULA=";
            public static string ValidarTipoAeronaveFormReporteH2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE = 2";
            public static string DatosHelicoptero = "SELECT MATRICULA, TO_CHAR(FECHA_INSPECCION_ANUAL,'DD/MM/YYYY') FECHA_INSPECCION_ANUAL,TO_CHAR(FECHA_DESTINO_REAL,'DD/MM/YYYY') FECHA_ULTIMO_VUELO,TRUNC(SYSDATE)-FECHA_INSPECCION_ANUAL DIAS_PARA_INSPECCION FROM AERONAVE INNER JOIN PLAN_VUELO ON AERONAVE.MATRICULA = PLAN_VUELO.AERONAVE_MATRICULA INNER JOIN PLAN_VUELO_REAL ON PLAN_VUELO.ID_VUELO = PLAN_VUELO_REAL.PLAN_VUELO_ID_VUELO WHERE ROWNUM = 1 AND MATRICULA=";
            public static string DatosHelicoptero2 = "AND TIPO_AERONAVE_ID_TIPO_AERONAVE=2 ORDER BY FECHA_DESTINO_REAL DESC";
            public static string ValidarExistenciaVuelos = "SELECT AERONAVE_MATRICULA FROM PLAN_VUELO_REAL WHERE AERONAVE_MATRICULA =";
            //FIN FORM REPORTE AERONAVES

            //MANTENEDOR USUARIO
            public static string ActualizarGridMantenedorUsuario = "SELECT RUT, CONTRASENA, NOMBRE_TIPO_USUARIO FROM USUARIO INNER JOIN TIPO_USUARIO ON USUARIO.TIPO_USUARIO_ID_TIPO_USUARIO = TIPO_USUARIO.ID_TIPO_USUARIO";
            public static string ActualizarUsuario = "UPDATE USUARIO SET CONTRASENA = ";
            public static string ActualizarUsuario2 = "TIPO_USUARIO_ID_TIPO_USUARIO = ";
            public static string ActualizarUsuario3 = "WHERE RUT = ";
            public static string TraerDatosUsuario = "SELECT RUT, CONTRASENA, NOMBRE_TIPO_USUARIO, TIPO_USUARIO_ID_TIPO_USUARIO FROM USUARIO INNER JOIN TIPO_USUARIO ON USUARIO.TIPO_USUARIO_ID_TIPO_USUARIO = TIPO_USUARIO.ID_TIPO_USUARIO WHERE RUT= ";
            public static string MantenedorUsuarioCbTipoUsuario = "SELECT RUT, CONTRASENA, NOMBRE_TIPO_USUARIO, TIPO_USUARIO_ID_TIPO_USUARIO FROM USUARIO INNER JOIN TIPO_USUARIO ON USUARIO.TIPO_USUARIO_ID_TIPO_USUARIO = TIPO_USUARIO.ID_TIPO_USUARIO WHERE RUT=";
            public static string MantenedorUsuarioCbTipoUsuarioEdit = "SELECT * FROM TIPO_USUARIO";
            public static string MantenedorUsuarioDelete = "DELETE FROM USUARIO WHERE RUT=";
            //FIN MANTENEDOR USUARIO

            //FORM VISTA PILOTO
            public static string ValidarEstadoPiloto = "SELECT RUT_PILOTO, ESTADO_ID_ESTADO FROM PILOTO WHERE RUT_PILOTO=";
            public static string ValidarEstadoPiloto2 = "AND ESTADO_ID_ESTADO ='2'";
            public static string ValidarEstadoPilotoFichaMedica = "SELECT RUT_PILOTO, ESTADO_ID_ESTADO FROM PILOTO WHERE RUT_PILOTO=";
            public static string ValidarEstadoPilotoFichaMedica2 = "AND ESTADO_ID_ESTADO ='3'";
            //FIN FORM VISTA PILOTO

            //FUNCION E-EMAIL
            public static string EnviarCorreo = "SELECT CORREO, NOMBRE_PILOTO, APELLIDO_PATERNO, APELLIDO_MATERNO FROM PILOTO WHERE RUT_PILOTO = ";
            public static string NombreCorreo = "aeronautica.prueba@gmail.com";
            public static string PassCorreo = ""+(conexion.AMNJD)+"";
            //FIN FUNCION E-MAIL

            //FORM CONSULTAR VUELOS REALES
            public static string BtnConsultaVuelos = "SELECT ID_PLAN_VUELO_REAL,TO_CHAR(FECHA_ORIGEN_REAL,'dd/MM/yyyy') FECHA_ORIGEN_REAL,TO_CHAR(FECHA_DESTINO_REAL,'dd/MM/yyyy')FECHA_DESTINO_REAL,RUT_PILOTO_PVR RUT_PILOTO,LICENCIA_PILOTO,RUT_COPILOTO,LICENCIA_COPILOTO,RUTA,NOMBRE_ORIGEN ORIGEN,NOMBRE_DESTINO DESTINO,NOMBRE_CONDICION CONDICION,NOMBRE_MISION MISION,AERONAVE_MATRICULA MATRICULA,NOMBRE_TIPO_AERONAVE TIPO_AERONAVE,NOMBRE_MODELO MODELO FROM PLAN_VUELO_REAL INNER JOIN ORIGEN ON PLAN_VUELO_REAL.ORIGEN_ID_ORIGEN = ORIGEN.ID_ORIGEN INNER JOIN DESTINO ON PLAN_VUELO_REAL.DESTINO_ID_DESTINO = DESTINO.ID_DESTINO INNER JOIN CONDICION ON PLAN_VUELO_REAL.CONDICION_ID_CONDICION = CONDICION.ID_CONDICION INNER JOIN MISION ON PLAN_VUELO_REAL.MISION_ID_MISION = MISION.ID_MISION INNER JOIN AERONAVE ON PLAN_VUELO_REAL.AERONAVE_MATRICULA = AERONAVE.MATRICULA INNER JOIN TIPO_AERONAVE ON AERONAVE.TIPO_AERONAVE_ID_TIPO_AERONAVE = TIPO_AERONAVE.ID_TIPO_AERONAVE INNER JOIN MODELO ON AERONAVE.MODELO_ID_MODELO = MODELO.ID_MODELO";
            //FIN FORM CONSULTAR VUELOS REALES

            public static string ConString = ""+(conexion.ConString)+"";




        }
    }
}
