drop table aeronave cascade constraints;
drop table provincia cascade constraints;
drop table comuna cascade constraints;
drop table componente cascade constraints;
drop table condicion cascade constraints;
drop table cond_tipo_cond cascade constraints;
drop table destino cascade constraints;
drop table mantenimiento cascade constraints;
drop table detalle_mantenimiento cascade constraints;
drop table fabricante cascade constraints;
drop table ficha_medica cascade constraints;
drop table licencia cascade constraints;
drop table mision cascade constraints;
drop table origen cascade constraints;
drop table pais cascade constraints;
drop table piloto cascade constraints;
drop table plan_vuelo cascade constraints;
drop table plan_vuelo_real cascade constraints;
drop table proveedor cascade constraints;
drop table region cascade constraints;
drop table taller_mecanico cascade constraints;
drop table tipo_aeronave cascade constraints;
drop table tipo_condicion cascade constraints;
drop table tipo_licencia cascade constraints;
drop table tipo_usuario cascade constraints;
drop table usuario cascade constraints;
drop table usuario_mision cascade constraints;
drop table usuario_plan_vuelo cascade constraints;
drop table sexo cascade constraints;
drop table estado cascade constraints;
drop table modelo cascade constraints;
drop table mantenimiento_historico cascade constraints;
drop table ficha_medica_historico cascade constraints;
drop sequence ID_VUELO;
drop sequence ID_COMPONENTE;
drop sequence ID_MISION;
drop sequence ID_FABRICANTE;
drop sequence ID_MANTENIMIENTO;
drop sequence ID_FICHA_MEDICA;
drop sequence ID_PLAN_VUELO_REAL;
drop sequence DETALLE_MANTENIMIENTO_ID;	
